[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Content-Type = "application/json"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://m8paintingtools.netlify.app/*"
  to = "https://www.m8paintingtools.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://m8paintingtools.netlify.app/*"
  to = "https://www.m8paintingtools.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ma8paintingtools.netlify.app/*"
  to = "https://www.m8paintingtools.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://ma8paintingtools.netlify.app/*"
  to = "https://www.m8paintingtools.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
